# Generated by Django 5.0.6 on 2024-06-19 08:26

import colorfield.fields
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("photoroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorPallete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                (
                    "colors",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=colorfield.fields.ColorField(
                            default="#FFFFFF",
                            image_field=None,
                            max_length=25,
                            samples=None,
                        ),
                        blank=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_palletes",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="colorpallete",
            constraint=models.UniqueConstraint(
                fields=("name",), name="photoroom_colorpallete_uniq"
            ),
        ),
    ]
